name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test application files
        run: |
          test -f app/index.html
          test -f app/Dockerfile

      - name: Build Docker image
        run: docker build -t production-app ./app

      - name: Deploy to Blue server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.BLUE_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 
            cd ~/Production-AWS-DevOps-Platform/app
            sudo docker stop blue-app || true
            sudo docker rm blue-app || true
            sudo docker build -t blue-app .
            sudo docker run -d --name blue-app -p 80:80 blue-app